# Generated by Django 4.2 on 2024-10-06 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='pictures/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(max_length=256, null=True)),
                ('user_id', models.CharField(max_length=256, null=True)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.picture')),
            ],
        ),
    ]
